# Generated by Django 4.2.4 on 2023-09-28 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group_chat', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('participants', models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizersRq',
            fields=[
                ('orgrq_id', models.IntegerField(primary_key=True, serialize=False)),
                ('orgrq_time', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrgStatus',
            fields=[
                ('org_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('org_stat', models.CharField(blank=True, max_length=45, null=True)),
                ('org_stat_rq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.organizersrq')),
            ],
        ),
        migrations.CreateModel(
            name='Steeze',
            fields=[
                ('steeze_id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster_gps_long', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=45, null=True)),
                ('steez_time', models.CharField(blank=True, max_length=45, null=True)),
                ('poster_gps_lati', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('fname', models.CharField(blank=True, max_length=45, null=True)),
                ('sname', models.CharField(blank=True, max_length=45, null=True)),
                ('dob', models.CharField(blank=True, max_length=45, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=145, null=True)),
                ('about', models.CharField(blank=True, max_length=45, null=True)),
                ('profilepic', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='test2app.userprofile')),
                ('org_stat', models.ForeignKey(blank=True, db_column='org_stat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.orgstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRq',
            fields=[
                ('vrq_id', models.AutoField(primary_key=True, serialize=False)),
                ('scanned_doc', models.CharField(blank=True, max_length=45, null=True)),
                ('vrq_time', models.CharField(blank=True, max_length=45, null=True)),
                ('v_requester', models.ForeignKey(blank=True, db_column='v_requester', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationStatus',
            fields=[
                ('idverification_status', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('vrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.verificationrq')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification',
            field=models.ForeignKey(blank=True, db_column='verification', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.verificationstatus'),
        ),
        migrations.CreateModel(
            name='SteezeLikes',
            fields=[
                ('like_id', models.IntegerField(primary_key=True, serialize=False)),
                ('like_time', models.CharField(blank=True, max_length=45, null=True)),
                ('liker', models.ForeignKey(blank=True, db_column='liker', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.userprofile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.steeze')),
            ],
        ),
        migrations.CreateModel(
            name='SteezeCom',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=45, null=True)),
                ('com_time', models.CharField(blank=True, max_length=45, null=True)),
                ('commentor', models.ForeignKey(blank=True, db_column='commentor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.userprofile')),
                ('stz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.steeze')),
            ],
        ),
        migrations.AddField(
            model_name='steeze',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.userprofile'),
        ),
        migrations.CreateModel(
            name='RelationRq',
            fields=[
                ('rel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('relatiion_stat', models.CharField(blank=True, max_length=45, null=True)),
                ('follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.userprofile')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='relationrq_user_set', to='test2app.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='organizersrq',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='test2app.userprofile'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='message_attachments/videos/')),
                ('image', models.FileField(blank=True, null=True, upload_to='message_attachments/images/')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='message_attachments/voice_notes/')),
                ('document', models.FileField(blank=True, null=True, upload_to='message_attachments/documents/')),
                ('gps_location', models.CharField(blank=True, max_length=255, null=True)),
                ('url_link', models.URLField(blank=True, max_length=255, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='test2app.chat')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flags',
            fields=[
                ('flag_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField()),
                ('flag_type', models.CharField(choices=[('flag_1', 'Flag 1'), ('flag_2', 'Flag 2')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlagRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=45)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_requests', to='test2app.flags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('idevent', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255)),
                ('event_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('event_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('requires_tickets', models.BooleanField(default=False)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_date_time', models.DateTimeField()),
                ('event_end_date_time', models.DateTimeField()),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
