# Generated by Django 5.0.1 on 2024-05-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
